logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    cn.itcast: debug
spring:
  rabbitmq:
    host: 192.168.188.188 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: itcast
    password: 123321
    virtual-host: /
    # 消息是否到达交换机
    publisher-confirm-type: correlated
    # 消息到了交换机后，是否到达队列
    publisher-returns: true
    template:
      mandatory: true
